services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
        #$projectDir: '%kernel.project_dir%'

    Markocupic\SacEventBlogBundle\:
        resource: ../src/
        exclude: ../src/{DependencyInjection,Model,Resources}

    Markocupic\SacEventBlogBundle\EventListener\FileUploadListener:
        arguments:
            - "@terminal42_fineuploader.uploader"


    Markocupic\SacEventBlogBundle\DataContainer\CalendarEventsBlog:
        arguments:
            - '@security.helper'
            - '@database_connection'
            - '@request_stack'
            - '@Markocupic\SacEventToolBundle\Download\BinaryFileDownload'
            - '%kernel.project_dir%'
            - '%sacevt.temp_dir%'
            - '%sac_event_blog.docx_export_template%'
            - '%sacevt.locale%'

    # Event blog list module
    Markocupic\SacEventBlogBundle\Controller\FrontendModule\EventBlogListController:
        arguments:
            - '@contao.framework'
            - '@contao.routing.scope_matcher'
            - '%kernel.project_dir%'
        public: true

    # Event blog reader module
    Markocupic\SacEventBlogBundle\Controller\FrontendModule\EventBlogReaderController:
        arguments:
            - '@contao.framework'
            - '@contao.routing.scope_matcher'
            - '@request_stack'
            - '@Codefog\HasteBundle\UrlParser'
            - '%kernel.project_dir%'
            - '%sacevt.locale%'
        public: true

    # Member dashboard module: list event reports and the form to generate new event reports
    Markocupic\SacEventBlogBundle\Controller\FrontendModule\MemberDashboardEventBlogListController:
        arguments:
            - '@contao.framework'
            - '@contao.routing.scope_matcher'
            - '@security.helper'
            - '@translator'
            - '@Codefog\HasteBundle\UrlParser'
        public: true

    # Member dashboard module: display the forms for writing new event reports
    Markocupic\SacEventBlogBundle\Controller\FrontendModule\MemberDashboardEventBlogWriteController:
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@contao.routing.scope_matcher'
            - '@request_stack'
            - '@translator'
            - '@Codefog\HasteBundle\UrlParser'
            - '@security.helper'
            - '@Codefog\HasteBundle\UrlParser'
            - '%kernel.project_dir%'
            - '%sac_event_blog.asset_dir%'
            - '%sacevt.locale%'
        public: true


    Markocupic\SacEventBlogBundle\Controller\Ajax\MemberDashboardWriteEventBlogController:
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@contao.csrf.token_manager'
            - '@request_stack'
            - '@security.helper'
            - '@translator'
            - '@Markocupic\SacEventToolBundle\Image\RotateImage'
            - '@Codefog\HasteBundle\UrlParser'
            - '%kernel.project_dir%'
            - '%contao.csrf_token_name%'
            - '%sacevt.locale%'
        public: true

    # Contao Backend Module "Maintenance": Delete no more used event blog media directories
    Markocupic\SacEventBlogBundle\ContaoBackendMaintenance\MaintainModuleEventBlog:
        public: true
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '%kernel.project_dir%'
            - '%sac_event_blog.asset_dir%'
            - '@monolog.logger.contao'
